CREATE PROCEDURE DropTables
AS
IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME='UserLoginInfo')
BEGIN
TRUNCATE TABLE UserLoginInfo
DROP TABLE UserLoginInfo
END
GO
IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME='StudentIDInfo')
BEGIN
TRUNCATE TABLE StudentIDInfo
DROP TABLE StudentIDInfo
END
GO
IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME='EmployeeIDInfo')
BEGIN
TRUNCATE TABLE EmployeeIDInfo
DROP TABLE EmployeeIDInfo
END
GO
IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME='IDCardDetails')
BEGIN
TRUNCATE TABLE IDCardDetails
DROP TABLE IDCardDetails
END
GO

